// <auto-generated />
using System;
using JobListings.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobListings.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250720115629_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("JobListings.Models.JobListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JobListings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "Toyota",
                            Description = "Develop Robust web application using ASP.NET Core MVC",
                            IsActive = true,
                            JobType = "Full-time",
                            Location = "Osaka, Japan",
                            PostedDate = new DateTime(2025, 7, 15, 17, 26, 28, 982, DateTimeKind.Local).AddTicks(4990),
                            Salary = 5794140m,
                            Title = "Software Development"
                        },
                        new
                        {
                            Id = 2,
                            Company = "Honda",
                            Description = "Develop Robust low level systems using C#",
                            IsActive = true,
                            JobType = "Full-time",
                            Location = "Tokyo, Japan",
                            PostedDate = new DateTime(2025, 7, 17, 17, 26, 28, 982, DateTimeKind.Local).AddTicks(5933),
                            Salary = 4282500m,
                            Title = "C# Development"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
